### ISSUE TITLE
Trouble Filtering with all matchlists OR including custom yaml file

### ISSUE THREAD

**Issue by lisajacobson** [chrisvfritz/language_filter#2]
I would like to include all match lists that are built into your gem, but Rails does not like two ways I tried setting them all to `matchlist:`:

`matchlist: [:hate, :violence],` or `matchlist: :hate, :violence,`

It's fine if this doesn't work with `language_filter`, but I was unable to use a yml file, too:
`matchlist: [File.join(Rails.root, "/config/language_filter/custom_list.yml")],` with the file in the right location with all the words from your default matchlists.

Looking forward to hearing from you. Great gem - we just need a more robust match list.

**Comment by chrisvfritz** [comment]
When matchlist is passed an array, it expects strings including optional regex patterns. If you point matchlist to a file pattern directly instead of an array with a file pattern inside, then including the custom yaml file should work.

**Comment by lisajacobson** [comment]
I tried the file path as a string but keep getting this error:
`LanguageFilter::UnkownContentFile (List content file "custom_list.yml'" can't be found.):`
I have tried moving the file around quite a bit, updating the respective file path. I even put it in the same directory as the file with the language filter object, so the above would seem to work, but that error is persistent.

**Comment by chrisvfritz** [comment]
Ahh, then it sounds like you're passing a relative file path, rather than an absolute one. An absolute path will look more like this:

```
/Users/username/code/my_project/config/my_matchlist.yml
```

What's weird though is that your example:

``` rb
File.join(Rails.root, "/config/language_filter/custom_list.yml")
```

_should_ actually produce an absolute path. 😕  Can you provide the full code that's producing this error?

**Comment by lisajacobson** [comment]
Thanks @chrisvfritz. Because I am unable to post the code and the yml approach didn't work, we ended up going with choosing a single match list. We plan to have someone monitor the language periodically, and our use of your gem is our first stab at content moderation. Thanks again.

**Comment by chrisvfritz** [comment]
No problem. I'll close this issue for now then, pending a reproduction. 😃
