### ISSUE TITLE
New at rails

### ISSUE THREAD

**Issue by opemily** [chrisvfritz/language_filter#3]
I was just wondering in what files I should be placing the filters in.

**Comment by chrisvfritz** [comment]
To make sure I'm understanding the question, can you provide more information please?

**Comment by opemily** [comment]
to create a new filter- do I place the (sex_filter = LanguageFilter::Filter.new matchlist: :sex, replacement: :stars) in the model  or the controller?

I am creating a forum and I would like posts to be filtered for language

**Comment by eoinshea** [comment]
i put it in my model file
just copied from the README and worked from there

**Comment by chrisvfritz** [comment]
@opemily You'd place it wherever you wanted to sanitize text. Using Rails, you'd probably want something [like this](https://github.com/chrisvfritz/language_filter#activemodel-integration) to sanitize a field.
